sudo: required
services:
  - docker

before_install:
  - docker build -t hamedsa/react-test -f ./client/Dockerfile.dev ./client
# - docker build API ...

script:
  - docker run -e CI=true hamedsa/react-test npm test
# - docker run myAPI ....

after_success:
  - docker build -t 1740021886/multi-client ./client
  - docker build -t 1740021886/multi-nginx ./nginx
  - docker build -t 1740021886/multi-server ./server
  - docker build -t 1740021886/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push 1740021886/multi-client
  - docker push 1740021886/multi-nginx
  - docker push 1740021886/multi-server
  - docker push 1740021886/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: Multidocker-env-1
  bucket_name: elasticbeanstalk-us-east-1-432612087802
  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
